### ISSUE TITLE
As a user, I want to be able to create a group in order to access group features.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#10]
- [x] sopra-fs22-group-33/server#98
- [x] sopra-fs22-group-33/server#97
- [x] sopra-fs22-group-33/server#96
- [x] sopra-fs22-group-33/server#95
- [x] sopra-fs22-group-33/server#94
- [x] sopra-fs22-group-33/client#60
