### ISSUE TITLE
As an invited user I want to be able to accept or decline the invitation in order to control access rights of others to my personal data.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#12]
- [ ] sopra-fs22-group-33/client#12
- [x] sopra-fs22-group-33/client#13
- [ ] sopra-fs22-group-33/client#14
