### ISSUE TITLE
As a team leader I want to be able to send an invitation to register through email in order to later collaborate through the system.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#14]
- [x] sopra-fs22-group-33/client#46
- [x] sopra-fs22-group-33/client#47
- [x] sopra-fs22-group-33/client#48
- [x] sopra-fs22-group-33/server#137
