### ISSUE TITLE
As a team leader, I want to set up a base plan for my team in order to get an optimized plan.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#18]
- [x] sopra-fs22-group-33/client#52
- [x] sopra-fs22-group-33/client#53
- [x] sopra-fs22-group-33/client#19
- [x] sopra-fs22-group-33/client#20
- [x] sopra-fs22-group-33/client#21
- [x] sopra-fs22-group-33/client#22
- [x] sopra-fs22-group-33/client#23
- [x] sopra-fs22-group-33/server#75
- [x] sopra-fs22-group-33/server#113
