### ISSUE TITLE
 As a user I want to be able to register by providing an email and password, and then choose my username in order to have access to the system

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#2]
- [x] sopra-fs22-group-33/server#111
- [x] sopra-fs22-group-33/client#7
- [x] sopra-fs22-group-33/client#8
- [x] sopra-fs22-group-33/server#114
- [x] sopra-fs22-group-33/client#10
- [x] sopra-fs22-group-33/server#100
- [x] sopra-fs22-group-33/server#99
