### ISSUE TITLE
As a user, I want to be able to manage my personal calendar, so my availability for shifts in groups is always adjusted automatically across all groups.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#21]
- [x] sopra-fs22-group-33/server#68
- [x] sopra-fs22-group-33/server#67
- [x] sopra-fs22-group-33/client#34
- [x] sopra-fs22-group-33/server#65
