### ISSUE TITLE
As a user, I want to be able to import my Google calendars, so I don’t need manually recreate all my appointments, vacations etc. in the calendar of the application.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#23]
- [x] sopra-fs22-group-33/client#35
- [ ] sopra-fs22-group-33/server#61
- [ ] sopra-fs22-group-33/server#60
- [ ] sopra-fs22-group-33/server#59
- [x] sopra-fs22-group-33/server#58
