### ISSUE TITLE
As a team member I want to set my general preferences for shifts for a particular team by picking the slots made by the team leader in order to get a better optimized calendar.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#26]
- [x] sopra-fs22-group-33/client#36
- [x] sopra-fs22-group-33/server#54
- [x] sopra-fs22-group-33/server#53
- [x] sopra-fs22-group-33/server#52
- [x] sopra-fs22-group-33/client#37
- [x] #112
- [x] #119
- [x] #147
