### ISSUE TITLE
As a team member I want to create high preferences (e.g. one specific day off/ highly preferred shift) in order to have a higher chance of getting the desired outcome in the optimized calendar.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#27]
- [x] sopra-fs22-group-33/client#38
- [ ] sopra-fs22-group-33/client#39
- [x] sopra-fs22-group-33/client#40
- [ ] sopra-fs22-group-33/client#41
- [x] sopra-fs22-group-33/client#111
- [x] sopra-fs22-group-33/client#110
- [x] sopra-fs22-group-33/client#42
- [x] sopra-fs22-group-33/server#43
- [ ] sopra-fs22-group-33/client#43
