### ISSUE TITLE
As a team member I want to participate in a game of snake if my high preferences collide with those of another user in order to resolve the dispute.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#28]
- [x] sopra-fs22-group-33/server#41
- [x] sopra-fs22-group-33/client#44
- [x] sopra-fs22-group-33/client#117
- [x] sopra-fs22-group-33/client#149
