### ISSUE TITLE
As a team member I want the results of the dispute-resolving snake game to solve all problems related to the collision in a clearly fair manner in order to not have to discuss anything else with the affected team member after.

### ISSUE THREAD

**Issue by UpstairsForest** [sopra-fs22-group-33/server#29]
- [x] sopra-fs22-group-33/client#109
- [x] sopra-fs22-group-33/server#35
- [x] sopra-fs22-group-33/server#34
- [x] sopra-fs22-group-33/server#33
- [x] sopra-fs22-group-33/server#32
- [x] sopra-fs22-group-33/server#31
- [ ] sopra-fs22-group-33/server#30
- [x] sopra-fs22-group-33/client#59
- [x] sopra-fs22-group-33/server#130
- [x] sopra-fs22-group-33/client#95
